### ISSUE TITLE
Connection interruptedby the remote host

### ISSUE THREAD

**Issue by kinerskiner** [OpenBypassProject/OpenBypass#1]
At the beggining I didn´t knew how to use it, but after figuring it out, and trying to use the MDM Bypass option on the application, appears this error on the screen: "an existing connection has been forced to be interrupted by the remote host".

I hope anyone can fix this problem, thanks.

**Comment by 0x14307** [comment]
Have you jailbroken your device yet? Plus, what device is it?

**Comment by 0x14307** [comment]
Also, it looks like you've already made this comment on Reddit regarding this. If I don't get a response back in 24 hours, I'll close this issue

**Comment by kinerskiner** [comment]
Tried jailbreaking the device with checkra.in, but it does not supports it, btw it’s an iPhone SE (2020) ios 14.4.1 
Which jailbreak do you recommend?

Enviado desde mi iPhone

**Comment by 0x14307** [comment]
You can't jailbreak an iPhone SE 2020. This issue will be closed.
